- .gitignore
- omnisharp-dotnet/Directory.Build.props
- omnisharp-dotnet/SonarLint.OmniSharp.Plugin.sln
- omnisharp-dotnet/build/DownloadOmniSharp.targets
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/packages.lock.json
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DownloadOmniSharp.targets
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/SonarLint.OmniSharp.Plugin.csproj
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/packages.lock.json
> Added targets to fetch and reference OmniSharp assemblies

- omnisharp-dotnet/SonarLint.OmniSharp.Plugin.sln
- omnisharp-dotnet/THIRD-PARTY-NOTICES
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/OmniSharp/Configuration.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/OmniSharp/CopiedCSharpDiagnosticWorkerWithAnalyzers.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/OmniSharp/DiagnosticExtensions.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/SonarLint.OmniSharp.Plugin.csproj
> Add OmniSharp license headers

- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/DiagnosticWorker/SonarLintDiagnosticWorkerTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/SonarLintDiagnosticWorker.cs
> Ignore compiler warnings and errors

- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/DiagnosticWorker/SonarAnalyzerAssembliesProviderTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/DiagnosticWorker/SonarAnalyzerCodeActionProviderTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/DiagnosticWorker/SonarLintDiagnosticWorkerTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/Rules/RuleDefinitionsRepositoryTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/Services/PingServiceTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/TestingInfrastructure/MefTestHelpers.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/TestingInfrastructure/SingleObjectImporter.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/packages.lock.json
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/SonarAnalyzerAssembliesProvider.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/SonarAnalyzerCodeActionProvider.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/DiagnosticWorker/SonarLintDiagnosticWorker.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/Rules/RuleDefinitionsRepository.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/SonarLint.OmniSharp.Plugin.csproj
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/packages.lock.json
> Use MEF 2.0 (System.Composition)

- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/Services/ConfigServiceTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/Services/ConfigService.cs
> Add config service

- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin.UnitTests/Services/SonarLintCodeCheckServiceTests.cs
- omnisharp-dotnet/src/SonarLint.OmniSharp.Plugin/Services/SonarLintCodeCheckService.cs
> Add code check service

- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarAnalyzerAssembliesProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarAnalyzerCodeActionProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintDiagnosticWorkerTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RuleDefinitionsRepositoryTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToAdditionalTextConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToReportDiagnosticsConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/RulesToSonarLintConfigurationConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/SonarLintConfigurationSerializerTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Services/DiagnosticsToCodeLocationsConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Services/SonarLintCodeCheckServiceTests.cs
- omnisharp-dotnet/src/Services.UnitTests/TestingInfrastructure/MefTestHelpers.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/AdditionalLocations/CodeLocation.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/OmniSharp/DiagnosticExtensions.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarAnalyzerAssembliesProvider.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarAnalyzerCodeActionProvider.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarLintDiagnosticWorker.cs
- omnisharp-dotnet/src/Services/Rules/RuleDefinition.cs
- omnisharp-dotnet/src/Services/Rules/RuleDefinitionsRepository.cs
- omnisharp-dotnet/src/Services/Rules/SonarLintXml/RulesToSonarLintConfigurationConverter.cs
- omnisharp-dotnet/src/Services/Rules/SonarLintXml/SonarLintConfigurationSerializer.cs
- omnisharp-dotnet/src/Services/Services/DiagnosticsToQuickFixConverter.cs
- low-risk changes e.g. making methods static, changing "new" syntax
Part of #54
> [2] Minor code cleanup

- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/RulesToSonarLintConfigurationConverterTests.cs
- omnisharp-dotnet/src/Services/Rules/SonarLintXml/RulesToSonarLintConfigurationConverter.cs
> Only includes rules with parameters in SonarLint config

- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToReportDiagnosticsConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Services/ConfigServiceTests.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/Services/Rules/RuleDefinition.cs
- omnisharp-dotnet/src/Services/Rules/RulesToReportDiagnosticsConverter.cs
- omnisharp-dotnet/src/Services/Services/ConfigService.cs
> Change RuleDefinitionsRepository to contain only active rules

- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/ActiveRuleDefinitionsRepositoryTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToAdditionalTextConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToReportDiagnosticsConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/RulesToSonarLintConfigurationConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Services/ConfigServiceTests.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/Services/Rules/ActiveRuleDefinition.cs
- omnisharp-dotnet/src/Services/Rules/ActiveRuleDefinitionsRepository.cs
- omnisharp-dotnet/src/Services/Rules/RuleDefinition.cs
- omnisharp-dotnet/src/Services/Rules/RulesToAdditionalTextConverter.cs
- omnisharp-dotnet/src/Services/Rules/RulesToReportDiagnosticsConverter.cs
- omnisharp-dotnet/src/Services/Rules/SonarLintXml/RulesToSonarLintConfigurationConverter.cs
- omnisharp-dotnet/src/Services/Services/ConfigService.cs
Cosmetics PR, just renames.
Part of #84
> Rename RuleDefinition to ActiveRuleDefinition

- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/SonarLintConfigurationSerializerTests.cs
- omnisharp-dotnet/src/Services/Rules/SonarLintXml/SonarLintConfigurationSerializer.cs
> Serialize SonarLint.xml without BOM

- its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
- omnisharp-plugin/pom.xml
- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/OmnisharpPlugin.java
- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/OmnisharpServer.java
- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/StreamConsumer.java
- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/protocol/OmnisharpEndpoints.java
- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/protocol/OmnisharpResponseProcessor.java
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpPluginTests.java
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpServerTests.java
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/protocol/OmnisharpEndpointsTests.java
The key change is that all synchronized methods are in the same class `OmniSharpServer`, to garantee that no concurrent request can be made while the server is starting/stopping
> Rework server/endpoint collaboration

- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToReportDiagnosticsConverterTests.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/Services/Rules/RulesToReportDiagnosticsConverter.cs
Fixes SLI-637 (https://jira.sonarsource.com/browse/SLI-637)
> Ignore unrecognized active rules

- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/RulesToReportDiagnosticsConverterTests.cs
- omnisharp-dotnet/src/Services/DiagnosticWorker/SonarLintAnalysisConfigProvider.cs
- omnisharp-dotnet/src/Services/Rules/RulesToReportDiagnosticsConverter.cs
* Ignore unrecognized active rule ids
Fixes SLI-637
> Ignore unrecognized active rules (#99)

- its/pom.xml
- omnisharp-dotnet/Directory.Build.props
- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintAnalysisConfigProviderTests.cs
- omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/SonarLintDiagnosticWorkerTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/RulesToSonarLintConfigurationConverterTests.cs
- omnisharp-dotnet/src/Services.UnitTests/Rules/SonarLintXml/SonarLintConfigurationSerializerTests.cs
- omnisharp-dotnet/src/Services.UnitTests/SonarLint.OmniSharp.DotNet.Services.UnitTests.csproj
- omnisharp-dotnet/src/Services.UnitTests/packages.lock.json
- omnisharp-dotnet/src/Services/SonarLint.OmniSharp.DotNet.Services.csproj
- omnisharp-dotnet/src/Services/packages.lock.json
Another merge of https://github.com/SonarSource/sonarlint-omnisharp/pull/102
> Upgrade to Omnisharp v1.38.0

- omnisharp-plugin/pom.xml
> Update analyzer to 8.36.1.44192

- omnisharp-plugin/pom.xml
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpServicesExtractorTests.java
> Update embedded C# analyzer to 8.46

- azure-pipelines.yml
- its/pom.xml
- its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
- its/src/test/projects/DotNet7Project/DotNet7Project.sln
- its/src/test/projects/DotNet7Project/DotNet7Project/DotNet7Project.csproj
- its/src/test/projects/DotNet7Project/DotNet7Project/Program.cs
- pom.xml
See https://github.com/SonarSource/sonar-dotnet/issues/7230
> Add an IT to reproduce FP with dotnet 7 projects

- omnisharp-plugin/pom.xml
- pom.xml
> SLI-1038: C# analyzer update

- azure-pipelines.yml
- its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
i.e. get the updated templates that fix the Mend agent error
Fixes https://sonarsource.atlassian.net/browse/SLI-1056
> Use v2.0.1 of pipelines-yaml-templates

- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/OmnisharpSensor.java
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpSensorTests.java
> SLVSCODE-603 update docs link with the new site

- omnisharp-plugin/pom.xml
> SLI-1156 Update C# analyzer to 9.13

- .gitignore
- azure-pipelines.yml
- its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
- its/src/test/projects/DotNet8Project/DotNet8Project.sln
- its/src/test/projects/DotNet8Project/DotNet8Project/DotNet8Project.csproj
- its/src/test/projects/DotNet8Project/DotNet8Project/Program.cs
This was already in the making before .NET 8 was released. Now as the analyzer is finally out, we can merge it 😄
> ITs for .NET 8

- omnisharp-plugin/pom.xml
https://github.com/SonarSource/sonarlint-omnisharp/issues/186
> SLI-1205 Update embedded C# analyzer to 9.15.0.81779

- .cirrus.yaml
> BUILD-6001: Sonarqube scan

- .cirrus.yaml
Scan results: https://saas-eu.whitesourcesoftware.com/Wss/WSS.html#!project;id=2542196
> BUILD-6063 Implement mend scan for maven

- .cirrus.yaml
> BUILD-6029: Validate stage

- .cirrus.yaml
Scan results 
- dotnet: https://saas-eu.whitesourcesoftware.com/Wss/WSS.html#!project;id=2542192
- maven: https://saas-eu.whitesourcesoftware.com/Wss/WSS.html#!project;id=2542196
> BUILD-6002 Implement mend scan

- omnisharp-plugin/pom.xml
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpServicesExtractorTests.java
[SLI-1546](https://sonarsource.atlassian.net/browse/SLI-1546)
[SLI-1546]: https://sonarsource.atlassian.net/browse/SLI-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1546 Update embedded C# analyzer to 9.32.0.97167

- .cirrus.yaml
[BUILD-6166](https://sonarsource.atlassian.net/browse/BUILD-6166)
[BUILD-6166]: https://sonarsource.atlassian.net/browse/BUILD-6166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUILD-6166 Use sonarlint-visualstudio image

- its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
- pom.xml
[SLOMNI-29](https://sonarsource.atlassian.net/browse/SLOMNI-29)
Part of SLVSCODE-929
[SLOMNI-29]: https://sonarsource.atlassian.net/browse/SLOMNI-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-29 Prepare release 1.25

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-30](https://sonarsource.atlassian.net/browse/SLOMNI-30)
[SLOMNI-30]: https://sonarsource.atlassian.net/browse/SLOMNI-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-30 Prepare for next development iteration

- omnisharp-plugin/pom.xml
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpSensorTests.java
- pom.xml
[SLOMNI-34](https://sonarsource.atlassian.net/browse/SLOMNI-34)
[SLOMNI-34]: https://sonarsource.atlassian.net/browse/SLOMNI-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-34 update C# analyzer 10.3 to 10.4

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-36](https://sonarsource.atlassian.net/browse/SLOMNI-36)
Part of SLVSCODE-967
[SLOMNI-36]: https://sonarsource.atlassian.net/browse/SLOMNI-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-36 Prepare for next development iteration

- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-39](https://sonarsource.atlassian.net/browse/SLOMNI-39)
[SLOMNI-39]: https://sonarsource.atlassian.net/browse/SLOMNI-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-39 Update embedded C# analyzer to 10.6.0.109712

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-40](https://sonarsource.atlassian.net/browse/SLOMNI-40)
[SLOMNI-40]: https://sonarsource.atlassian.net/browse/SLOMNI-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-40 Prepare next development iteration

- .github/workflows/PullRequestClosed.yml
[SLOMNI-42](https://sonarsource.atlassian.net/browse/SLOMNI-42)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLOMNI-42]: https://sonarsource.atlassian.net/browse/SLOMNI-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-42 Autoclose issues created by Jira integration

- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-43](https://sonarsource.atlassian.net/browse/SLOMNI-43)
[SLOMNI-43]: https://sonarsource.atlassian.net/browse/SLOMNI-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-43 Update embedded C# analyzer to 10.7.0.110445

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-45](https://sonarsource.atlassian.net/browse/SLOMNI-45)
[SLOMNI-45]: https://sonarsource.atlassian.net/browse/SLOMNI-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-45 Prepare next development iteration

- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-47](https://sonarsource.atlassian.net/browse/SLOMNI-47)
[SLOMNI-47]: https://sonarsource.atlassian.net/browse/SLOMNI-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-47 Update embedded C# analyzer to 10.8.0.113526

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-48](https://sonarsource.atlassian.net/browse/SLOMNI-48)
[SLOMNI-48]: https://sonarsource.atlassian.net/browse/SLOMNI-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-48 Prepare for the next release

- .cirrus.yaml
[BUILD-8000](https://sonarsource.atlassian.net/browse/BUILD-8000)
[BUILD-8000]: https://sonarsource.atlassian.net/browse/BUILD-8000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUILD-8000 Update branch name for AMI QA

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-51](https://sonarsource.atlassian.net/browse/SLOMNI-51)
[SLOMNI-51]: https://sonarsource.atlassian.net/browse/SLOMNI-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-51 Prepare for next development iteration

- .cirrus.yaml
[SLOMNI-52](https://sonarsource.atlassian.net/browse/SLOMNI-52)
[SLOMNI-52]: https://sonarsource.atlassian.net/browse/SLOMNI-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-52 Update branch name for AMI QA

- omnisharp-plugin/src/main/java/org/sonarsource/sonarlint/omnisharp/OmnisharpSensor.java
- omnisharp-plugin/src/test/java/org/sonarsource/sonarlint/omnisharp/OmnisharpSensorTests.java
[SLOMNI-54](https://sonarsource.atlassian.net/browse/SLOMNI-54)
[SLOMNI-54]: https://sonarsource.atlassian.net/browse/SLOMNI-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-54 Fix dead link in log message

- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-55](https://sonarsource.atlassian.net/browse/SLOMNI-55)
[SLOMNI-55]: https://sonarsource.atlassian.net/browse/SLOMNI-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-55 Update embedded C# analyzer to 10.10.1.116480

- its/pom.xml
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-56](https://sonarsource.atlassian.net/browse/SLOMNI-56)
[SLOMNI-56]: https://sonarsource.atlassian.net/browse/SLOMNI-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-56 Prepare for next development iteration

- its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
- pom.xml
[SLOMNI-49](https://sonarsource.atlassian.net/browse/SLOMNI-49)
[SLOMNI-49]: https://sonarsource.atlassian.net/browse/SLOMNI-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-49 Remove deprecated code

- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-59](https://sonarsource.atlassian.net/browse/SLOMNI-59)
https://sonarsource.atlassian.net/browse/SLI-2109
[SLOMNI-59]: https://sonarsource.atlassian.net/browse/SLOMNI-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-59 Update embedded C# analyzer to 10.13.0.120203

- .github/workflows/build_scan_dotnet.sh
- .github/workflows/install_dependencies.sh
- .github/workflows/resources/settings.xml
- .github/workflows/shadow_scans.yml
- mise.toml
- pom.xml
[SLOMNI-61](https://sonarsource.atlassian.net/browse/SLOMNI-61)
[SLOMNI-61]: https://sonarsource.atlassian.net/browse/SLOMNI-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-61 Scan project on SQC EU and US

- omnisharp-dotnet/src/Services.UnitTests/SonarLint.OmniSharp.DotNet.Services.UnitTests.csproj
- omnisharp-dotnet/src/Services.UnitTests/packages.lock.json
- omnisharp-plugin/pom.xml
- pom.xml
[SLOMNI-69](https://sonarsource.atlassian.net/browse/SLOMNI-69)
[SLOMNI-69]: https://sonarsource.atlassian.net/browse/SLOMNI-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLOMNI-69 Update dependencies
